name: ai-competition
channels:
  - defaults
dependencies:
  - python=3.9.16
  - pip
  - pip:
    - arcade==2.6.17
    - attrs==22.2.0
    - cffi==1.15.1
    - cloudpickle==2.2.1
    - gym==0.26.2
    - gym-notices==0.0.8
    - gymnasium==0.27.1
    - gymnasium-notices==0.0.1
    - importlib-metadata==6.0.0
    - jax-jumpy==0.2.0
    - numpy
    - pettingzoo==1.22.3
    - pillow==9.3.0
    - pycparser==2.21
    - pygame==2.1.2
    - pyglet==2.0.dev23
    - pymunk==6.4.0
    - pytiled-parser==2.2.0
    - typing-extensions==4.4.0
    - zipp==3.11.0
